Started by user [8mha:////4KBTASWJbjWEO2b8b2W+ZJbFwJCejfu/iYw42Tli1QbRAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZu/dLi1CL9xJTczDwACG0V4sAAAAA=[0mJenkins Admin
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/ansible-test
[ansible-test] $ /bin/sh -xe /tmp/jenkins4891641734967871637.sh
+ cp /var/jenkins_home/ansible/ansible.cfg /var/jenkins_home/workspace/ansible-test
[ansible-test] $ ansible-playbook /var/jenkins_home/ansible/play.yml -i /var/jenkins_home/ansible/hosts -f 5
/usr/local/lib/python3.5/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.
  from cryptography.exceptions import InvalidSignature

PLAY [test1] *******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [test1]

TASK [shell] *******************************************************************
changed: [test1]

PLAY RECAP *********************************************************************
test1                      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Finished: SUCCESS
